### ISSUE TITLE
enable per-shape opacity and weight

### ISSUE THREAD

**Issue by sbromberger** [ccbest/geostructures#53]
Not to jump to the solution, but allowing the geoshape to have a dictionary of attributes that get passed to whatever rendering engine is used would be an easy way to take care of this.

**Comment by ccbest** [comment]
Cleaning out old issues - I believe this is now possible using shape properties? 

Whatever engine being used should be able to receive the props and use them accordingly, e.g. storing a property `shape.set_property('style', {'color': 'red'})` and rendering the shape in folium (via `folium.GeoJson`) will result in the shape being red.

If this requirement is now met let me know so I can close the issue
